research_task:
  description: >
    Analyze the todos {todos} and provide a detailed report
  expected_output: >
    An analysis of my todos and also give me a few todos based on my todos
  agent: researcher
