services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - ollama
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
      - OLLAMA_HOST=http://ollama
      - OLLAMA_PORT=11434
    # volumes:
    #   - ./wait-for-it.sh:/wait-for-it.sh
    # command: ["/bin/sh", "-c", "/wait-for-it.sh db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      # - ollama
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
      # - OLLAMA_HOST=ollama
      # - OLLAMA_PORT=11434
      # - OLLAMA_BASE_URL=http://localhost:11434

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A tasks.celery_app beat --loglevel=info
    depends_on:
      - redis
      # - ollama
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/data

volumes:
  postgres_data:
  ollama_data:
  qdrant_data: